name: setup-linux
runs:
  using: composite
  steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # NOTE: At the time of writing, "apt install g++" on ubuntu-latest gives you g++ v13. The desired g++ version is >=14, and the only
      #       way to do that at this point is to explicitly run "apt install g++-14". In the future, it may be that ubuntu-latest changes 
      #       to a version of Ubuntu where "apt install g++" installs g++ v14 instead of v13, or even a later version than v14 (at which
      #       point we'd be pointing to an outdate version / the package might have been removed).
      - name: Install deps
        run: |
          sudo apt-get update
          # Install g++ and gcc.
          sudo apt-get install -y gcc-14 g++-14
          # Register g++-14/gcc-14 as the system default g++/gcc-14.
          #
          # NOTE: You may be able to replace this step by simply running the following before invoking meson in the step below this one:
          #
          #         export CC="$BREW_BIN/gcc-$GCC_VER"
          #         export CXX="$BREW_BIN/g++-$GCC_VER"
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100  # Include g++-14 as an alernative to g++
          sudo update-alternatives --set g++ /usr/bin/g++-14                       # Select g++-14 as the alternative for gcc
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100  # Include gcc-14 as alternative to gcc
          sudo update-alternatives --set gcc /usr/bin/gcc-14                       # Select gcc-14 as the alternative for gcc
          # Install meson and deps required by meson.
          sudo apt-get install -y pkg-config  # Required by meson to find dependencies?
          python -m pip install --upgrade pip
          python -m pip install meson ninja   # Install meson - ninja is needed by meson to do the actual compiling
          {% if cookiecutter.include_python_extension != 'false' -%}
          # Install python requirements.
          python -m pip install build  # Required for building python extension
          {%- endif %}
          {% if cookiecutter.include_python_extension == 'true_with_numpy' -%}
          python -m pip install numpy
          {%- endif %}
          {% if cookiecutter.min_boost_version != 'na' -%}
          # Install boost.
          sudo apt-get install -y libboost-all-dev
          {%- endif %}
          {% if cookiecutter.include_doxygen -%}
          # Install doxygen.
          sudo apt-get install -y doxygen graphviz  # Required for building docs
          {%- endif %}
