# By default, Windows runners come preloaded with Microsoft's Visual C++ as a compiler. To reduce variability from different C++ compilers
# supporting different compiling features, different language features, and having different compilation idiosyncrasies/bugs, everything is
# explicitly targeting GCC for compiling and linking.
#
# NOTE: To keep things as simple as possible, building is happening through msys2 for everything (compiler, build system, anything python
#       related, etc...). The hope is that msys2's package manager (pacman) will always contain relatively recent versions of whatever it
#       is that's being pulled in.
#
# WARNING: Notice that numpy is being pulled in via pacman instead of "pip install numpy". The pacman version includes prebuilt numpy
#          binaries where as "pip install numpy" will attempt to build those binaries from scratch (takes a very long time).
name: setup-windows
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install msys2
      shell: powershell
      run: |
        choco install msys2 -y
        # Create shell to launch msys commands
        echo @echo off> msys.bat
        echo "C:\msys64\ucrt64\usr\bin\bash.exe" -lc "%%*" >> msys.bat
        echo exit /b %%ERRORLEVEL%% >> msys.bat
        # Update
        .\msys.bat "pacman -Syuu --noconfirm"
    - name: Install deps
      shell: powershell
      run: |
        .\msys.bat "pacman -Sy --noconfirm \
          mingw-w64-ucrt-x86_64-toolchain \
          mingw-w64-ucrt-x86_64-boost \
          mingw-w64-ucrt-x86_64-python \
          mingw-w64-ucrt-x86_64-python-pip \
          mingw-w64-ucrt-x86_64-meson \
          mingw-w64-ucrt-x86_64-ninja \
          mingw-w64-ucrt-x86_64-pkg-config \
          {% if cookiecutter.include_python_extension != 'false' -%}
          mingw-w64-ucrt-x86_64-python-build \
          {%- endif %}
          {% if cookiecutter.include_python_extension == 'true_with_numpy' -%}
          mingw-w64-ucrt-x86_64-python-numpy \
          {%- endif %}
          {% if cookiecutter.include_doxygen -%}
          mingw-w64-ucrt-x86_64-doxygen \
          mingw-w64-ucrt-x86_64-graphviz \
          {%- endif %}"